public enum GameConclusionType
{
    NONE,
    CHECKMATE,
    STALEMATE,
    RESIGNATION,
    TIMEOUT,
    THREEFOLD_REPETITION,
    FIFTY_MOVE_RULE,
    AGREED_DRAW,
    INSUFFICIENT_MATERIAL,
    ABANDONED,
    LEVEL_CLEARED
}